DEFINE_ACTION_FUNCTION setup_pst_items
BEGIN
  LAUNCH_ACTION_FUNCTION grand_unified_installer
    STR_VAR
    tra		= "pst_items"
  END

 
  ACTION_BASH_FOR "%MOD_FOLDER%/%component_loc%/include" "^.*\.tpa$"
  BEGIN
    OUTER_TEXT_SPRINT file "%BASH_FOR_RES%"
    ACTION_TO_LOWER file

    LAUNCH_ACTION_FUNCTION run
      STR_VAR
      file
      location	= "include"
      tra	= "item_pack"
    END
  END
END	// setup_pst_items


