DEFINE_ACTION_FUNCTION item_pack_postproc
BEGIN
  LAUNCH_ACTION_FUNCTION check_ini
    STR_VAR
    ini         = "visible_ioun_stones"
    RET
    visible_ioun_stones = value
  END


  // Adjust prices of Staff of Air +2 and Staff of Fire +2 for consistency

  ACTION_IF is_bg2
  BEGIN
    LAUNCH_ACTION_FUNCTION edit_item
      STR_VAR
      item		= "staf15 staf17"
      editstring	= "price=>15000"
    END
  END


  // Visible Ioun Stones

  ACTION_IF visible_ioun_stones
  BEGIN
    ACTION_BASH_FOR "override" "mh#vsio.\.bam"
    BEGIN
      LAUNCH_ACTION_FUNCTION install_vvc
        STR_VAR
        vvc		= "sporbit=>%BASH_FOR_RES%"
        location	= "graphics"
        editstring	= "anim=>%BASH_FOR_RES%"
      END
    END

    MAKE_PATCH
      add_effect_global_inline=>~opcode=>215 target=>1 timing=>2 resource=>"object_index from [mh#vsio1 mh#vsio2 mh#vsio3 mh#vsio4 mh#vsio4 mh#vsio3 mh#vsio5]"~
    END

    LAUNCH_ACTION_FUNCTION edit_item
      STR_VAR
      item	= "mh#ioun1 mh#ioun2 mh#ioun3 mh#ioun4 mh#ioun5 mh#ioun6 mh#ioun7"
      edits	= "patch_data"
    END
  END
END	// item_pack_postproc


