DEFINE_ACTION_FUNCTION place_items_in_bg1
BEGIN
  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "brokks_forge"
    tra		= "brokks_forge"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "phendras_scrolls"
    tra		= "phendras_scrolls"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "gem_of_seeing"
    tra		= "gem_of_seeing"
  END

  LAUNCH_ACTION_FUNCTION run
    STR_VAR
    file	= "other_bg1_locations"
  END
END	// place_items_in_bg1


