DEFINE_ACTION_FUNCTION ries_kensiddar
BEGIN
  // NB: This assumes the shared/lore changes have been applied and the
  // owner of the Northern Light Inn in Nashkel is a wizard named
  // Ries Kensiddar.

  LAUNCH_ACTION_FUNCTION install
    STR_VAR
    file        = "ries_kensiddar.d"
    location    = "dialogs"
  END

  ADD_JOURNAL @3 @8

  LAUNCH_ACTION_FUNCTION erase_journal_entries_on_bg2_transition
    STR_VAR
    dialog      = "%tutu_var%innkn2"
  END
END	// ries_kensiddar


