IF
  HasItem("mh#swrd4", PLAYER1)
  Or(16)
    AreaCheck("AR0414")
    AreaCheck("AR0516")
    AreaCheck("AR0517")
    AreaCheck("AR0518")
    AreaCheck("AR0519")
    AreaCheck("AR0520")
    AreaCheck("AR0521")
    AreaCheck("AR2900")
    AreaCheck("AR2901")
    AreaCheck("AR2902")
    AreaCheck("AR2903")
    AreaCheck("AR2904")
    AreaCheck("AR2905")
    AreaCheck("AR2906")
    AreaCheck("AR4500")
    AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swd4a", "mh#swrd4", PLAYER1)
    DisplayStringHead(PLAYER1, @0)
END

IF
  HasItem("mh#swd4a", PLAYER1)
  !AreaCheck("AR0414")
  !AreaCheck("AR0516")
  !AreaCheck("AR0517")
  !AreaCheck("AR0518")
  !AreaCheck("AR0519")
  !AreaCheck("AR0520")
  !AreaCheck("AR0521")
  !AreaCheck("AR2900")
  !AreaCheck("AR2901")
  !AreaCheck("AR2902")
  !AreaCheck("AR2903")
  !AreaCheck("AR2904")
  !AreaCheck("AR2905")
  !AreaCheck("AR2906")
  !AreaCheck("AR4500")
  !AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swrd4", "mh#swd4a", PLAYER1)
    DisplayStringHead(PLAYER1, @1)
END


IF
  HasItem("mh#swrd4", PLAYER2)
  Or(16)
    AreaCheck("AR0414")
    AreaCheck("AR0516")
    AreaCheck("AR0517")
    AreaCheck("AR0518")
    AreaCheck("AR0519")
    AreaCheck("AR0520")
    AreaCheck("AR0521")
    AreaCheck("AR2900")
    AreaCheck("AR2901")
    AreaCheck("AR2902")
    AreaCheck("AR2903")
    AreaCheck("AR2904")
    AreaCheck("AR2905")
    AreaCheck("AR2906")
    AreaCheck("AR4500")
    AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swd4a", "mh#swrd4", PLAYER2)
    DisplayStringHead(PLAYER2, @0)
END

IF
  HasItem("mh#swd4a", PLAYER2)
  !AreaCheck("AR0414")
  !AreaCheck("AR0516")
  !AreaCheck("AR0517")
  !AreaCheck("AR0518")
  !AreaCheck("AR0519")
  !AreaCheck("AR0520")
  !AreaCheck("AR0521")
  !AreaCheck("AR2900")
  !AreaCheck("AR2901")
  !AreaCheck("AR2902")
  !AreaCheck("AR2903")
  !AreaCheck("AR2904")
  !AreaCheck("AR2905")
  !AreaCheck("AR2906")
  !AreaCheck("AR4500")
  !AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swrd4", "mh#swd4a", PLAYER2)
    DisplayStringHead(PLAYER2, @1)
END


IF
  HasItem("mh#swrd4", PLAYER3)
  Or(16)
    AreaCheck("AR0414")
    AreaCheck("AR0516")
    AreaCheck("AR0517")
    AreaCheck("AR0518")
    AreaCheck("AR0519")
    AreaCheck("AR0520")
    AreaCheck("AR0521")
    AreaCheck("AR2900")
    AreaCheck("AR2901")
    AreaCheck("AR2902")
    AreaCheck("AR2903")
    AreaCheck("AR2904")
    AreaCheck("AR2905")
    AreaCheck("AR2906")
    AreaCheck("AR4500")
    AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swd4a", "mh#swrd4", PLAYER3)
    DisplayStringHead(PLAYER3, @0)
END

IF
  HasItem("mh#swd4a", PLAYER3)
  !AreaCheck("AR0414")
  !AreaCheck("AR0516")
  !AreaCheck("AR0517")
  !AreaCheck("AR0518")
  !AreaCheck("AR0519")
  !AreaCheck("AR0520")
  !AreaCheck("AR0521")
  !AreaCheck("AR2900")
  !AreaCheck("AR2901")
  !AreaCheck("AR2902")
  !AreaCheck("AR2903")
  !AreaCheck("AR2904")
  !AreaCheck("AR2905")
  !AreaCheck("AR2906")
  !AreaCheck("AR4500")
  !AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swrd4", "mh#swd4a", PLAYER3)
    DisplayStringHead(PLAYER3, @1)
END


IF
  HasItem("mh#swrd4", PLAYER4)
  Or(16)
    AreaCheck("AR0414")
    AreaCheck("AR0516")
    AreaCheck("AR0517")
    AreaCheck("AR0518")
    AreaCheck("AR0519")
    AreaCheck("AR0520")
    AreaCheck("AR0521")
    AreaCheck("AR2900")
    AreaCheck("AR2901")
    AreaCheck("AR2902")
    AreaCheck("AR2903")
    AreaCheck("AR2904")
    AreaCheck("AR2905")
    AreaCheck("AR2906")
    AreaCheck("AR4500")
    AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swd4a", "mh#swrd4", PLAYER4)
    DisplayStringHead(PLAYER4, @0)
END

IF
  HasItem("mh#swd4a", PLAYER4)
  !AreaCheck("AR0414")
  !AreaCheck("AR0516")
  !AreaCheck("AR0517")
  !AreaCheck("AR0518")
  !AreaCheck("AR0519")
  !AreaCheck("AR0520")
  !AreaCheck("AR0521")
  !AreaCheck("AR2900")
  !AreaCheck("AR2901")
  !AreaCheck("AR2902")
  !AreaCheck("AR2903")
  !AreaCheck("AR2904")
  !AreaCheck("AR2905")
  !AreaCheck("AR2906")
  !AreaCheck("AR4500")
  !AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swrd4", "mh#swd4a", PLAYER4)
    DisplayStringHead(PLAYER4, @1)
END


IF
  HasItem("mh#swrd4", PLAYER5)
  Or(16)
    AreaCheck("AR0414")
    AreaCheck("AR0516")
    AreaCheck("AR0517")
    AreaCheck("AR0518")
    AreaCheck("AR0519")
    AreaCheck("AR0520")
    AreaCheck("AR0521")
    AreaCheck("AR2900")
    AreaCheck("AR2901")
    AreaCheck("AR2902")
    AreaCheck("AR2903")
    AreaCheck("AR2904")
    AreaCheck("AR2905")
    AreaCheck("AR2906")
    AreaCheck("AR4500")
    AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swd4a", "mh#swrd4", PLAYER5)
    DisplayStringHead(PLAYER5, @0)
END

IF
  HasItem("mh#swd4a", PLAYER5)
  !AreaCheck("AR0414")
  !AreaCheck("AR0516")
  !AreaCheck("AR0517")
  !AreaCheck("AR0518")
  !AreaCheck("AR0519")
  !AreaCheck("AR0520")
  !AreaCheck("AR0521")
  !AreaCheck("AR2900")
  !AreaCheck("AR2901")
  !AreaCheck("AR2902")
  !AreaCheck("AR2903")
  !AreaCheck("AR2904")
  !AreaCheck("AR2905")
  !AreaCheck("AR2906")
  !AreaCheck("AR4500")
  !AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swrd4", "mh#swd4a", PLAYER5)
    DisplayStringHead(PLAYER5, @1)
END


IF
  HasItem("mh#swrd4", PLAYER6)
  Or(16)
    AreaCheck("AR0414")
    AreaCheck("AR0516")
    AreaCheck("AR0517")
    AreaCheck("AR0518")
    AreaCheck("AR0519")
    AreaCheck("AR0520")
    AreaCheck("AR0521")
    AreaCheck("AR2900")
    AreaCheck("AR2901")
    AreaCheck("AR2902")
    AreaCheck("AR2903")
    AreaCheck("AR2904")
    AreaCheck("AR2905")
    AreaCheck("AR2906")
    AreaCheck("AR4500")
    AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swd4a", "mh#swrd4", PLAYER6)
    DisplayStringHead(PLAYER6, @0)
END

IF
  HasItem("mh#swd4a", PLAYER6)
  !AreaCheck("AR0414")
  !AreaCheck("AR0516")
  !AreaCheck("AR0517")
  !AreaCheck("AR0518")
  !AreaCheck("AR0519")
  !AreaCheck("AR0520")
  !AreaCheck("AR0521")
  !AreaCheck("AR2900")
  !AreaCheck("AR2901")
  !AreaCheck("AR2902")
  !AreaCheck("AR2903")
  !AreaCheck("AR2904")
  !AreaCheck("AR2905")
  !AreaCheck("AR2906")
  !AreaCheck("AR4500")
  !AreaCheck("AR6200")
THEN
  RESPONSE #100
    TakeItemReplace("mh#swrd4", "mh#swd4a", PLAYER6)
    DisplayStringHead(PLAYER6, @1)
END


