DEFINE_ACTION_FUNCTION bg2_pst_items
BEGIN
  ACTION_IF is_bg2
  BEGIN
    // ========
    // Saradush
    // ========

    // Arcana Archives
    //
    // mh#pst01 - Ring of Thex

    sto.edit[25spell]
    [
      m.item.clone{s_resref := "mh#pst01";;s_charges_1 = 0;;s_charges_2 = 0;;s_charges_3 = 0;;s_identified = 1;;s_number_in_stock = 1|match=~"%s_resref%"=="ring02"~}
    ]
  END	// is_bg2
END	// bg2_pst_items


