DEFINE_ACTION_FUNCTION place_iwd_items_in_stores
BEGIN
  MAKE_PATCH
    clone_item_inline'1=>~match=>"item_resource = potn20" item_resource=>"mh#iwd09" state_identified=>1~
    clone_item_inline'2=>~match=>"item_resource = dart02" item_resource=>"mh#iwd05" state_identified=>1~
  END

  LAUNCH_ACTION_FUNCTION edit_all_stores
    STR_VAR
    edits	= "patch_data"
  END
END	// place_iwd_items_in_stores


